# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Harsh Nakhva
# Description of the Site
description: Welcome to my page
# URL of Image of the Site
site-image: /assets/images/myself1.jpg
# Keywords of the Site
site-keywords: harsh nakhva, Harsh Nakhva, Harsh052001, harsh
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: h.nakhva2001@gmail.com
facebook_username: harsh.nakhva.5
twitter_username: harsh_nakhva
instagram_username: __rs_harsh_45__
linkedin_username: harsh-nakhva-400381212
github_username:  Harsh052001
telegram_username: Harsh052001

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Harsh052001

# Name of the Author
author-name: Harsh Nakhva
# URL for the Image of the Author
author-image: assets/images/myself1.jpg
# 60 Words About the Author
author-about: Harsh Nakhva is young and passionate Python coder, who has a good command in Python, HTML, CSS, Js. Also, he is a creative graphic designer and enthusiastic techie. For more information, you can contact me via mail and social media.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Harsh052001

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url:  https://github.com/Harsh052001

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
